---
- name: controll user
  hosts: all
  tasks:
    - name: create group
      ansible.builtin.group:
        name: student
        state: present
        gid: 1008

    - name: add user
      ansible.builtin.user:
        name: okjaeook
        uid: 2024
        shell: /sbin/nologin
        group: student
        groups: wheel
